version: '3.8'

services:
  trackmaster:
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG#v}
    ports:
      - "8000:8000"
    environment:
      - TRACKMASTER_VERSION=${CI_COMMIT_TAG#v}
      - LOG_LEVEL=INFO
    volumes:
      - ./uploads:/tmp/uploads
      - ./outputs:/tmp/outputs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
